### ISSUE TITLE
Compile error during the written-tutorial

### ISSUE THREAD

**Issue by DanDoes** [mroshaw/mroshaw.github.io#10]
> ![image](https://github.com/mroshaw/mroshaw.github.io/assets/6108209/70917638-d40d-40c5-aaaa-06b5ae3a7c8f)
[CS0052](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0052?f1url=%3FappId%3Droslyn%26k%3Dk(CS0052)): Inconsistent accessibility: field type 'ModOptions' is less accessible than field 'HelloWorldPlugin.ModOptions'

(Happens on [this step](https://mroshaw.github.io/Subnautica/yourfirstmod/enhancingthemod.html))

Took me a while but I eventually realized the culprit: ModOptions.cs class starts as "internal" but then sneakily changes to "public":
> ![image](https://github.com/mroshaw/mroshaw.github.io/assets/6108209/657ea667-df03-48d8-8906-a24aac93f098)
(I didn't notice the change and leaving it at "internal" causes that error.)

It's lucky you showed the full content of the file every time! Very helpful - without that I wouldn't've noticed the tiny difference.

**Comment by mroshaw** [comment]
Awesome, thanks for taking the time to log this as an issue. I'm going to make a few updates to the tutorial next week, so I'll add this to the list.

**Comment by mroshaw** [comment]
This is now fixed: https://mroshaw.github.io/Subnautica/yourfirstmod/enhancingthemod.html

**Comment by mroshaw** [comment]
Updated and pushed to docs repo.
